services:
  - type: web
    name: ctf-platform
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn ctf_platform.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*" # You should narrow this to your actual domain after deploy
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3
      - key: PYTHON_VERSION
        value: 3.10.0
